{"name": "test_create_auth_with_excel[user_cred1]", "status": "broken", "statusDetails": {"message": "KeyError: 'useername'", "trace": "user_cred = {'password': 'password124', 'username': 'admin123'}\n\n    @pytest.mark.parametrize(\"user_cred\", read_credentials_from_excel(os.getcwd() + \"/TestData_DDTesting.xlsx\"))\n    def test_create_auth_with_excel(user_cred):\n>       username = user_cred[\"useername\"]\nE       KeyError: 'useername'\n\nDDTesting_Better.py:38: KeyError"}, "parameters": [{"name": "user_cred", "value": "{'username': 'admin123', 'password': 'password124'}"}], "start": 1712654465015, "stop": 1712654465015, "uuid": "43fc390e-b24d-4305-a5ad-907758be1e5a", "historyId": "51b4aab302fb1106016fc20de230c26d", "testCaseId": "f9a4cb542c5c0a69195291e9a6a82ff9", "fullName": "tests.test.DataDrivenTesting.DDTesting_Better#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.DataDrivenTesting"}, {"name": "suite", "value": "DDTesting_Better"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "13948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.DataDrivenTesting.DDTesting_Better"}]}