{"name": "test_create_auth_with_excel[user_cred0]", "status": "broken", "statusDetails": {"message": "KeyError: 'useername'", "trace": "user_cred = {'password': 'password123', 'username': 'admin'}\n\n    @pytest.mark.parametrize(\"user_cred\", read_credentials_from_excel(os.getcwd() + \"/TestData_DDTesting.xlsx\"))\n    def test_create_auth_with_excel(user_cred):\n>       username = user_cred[\"useername\"]\nE       KeyError: 'useername'\n\nDDTesting_Better.py:38: KeyError"}, "parameters": [{"name": "user_cred", "value": "{'username': 'admin', 'password': 'password123'}"}], "start": 1712654464942, "stop": 1712654464942, "uuid": "e442ae6e-6ffa-4d08-bb49-06e60ffffe94", "historyId": "580376ba3dc4579667227b420768938e", "testCaseId": "f9a4cb542c5c0a69195291e9a6a82ff9", "fullName": "tests.test.DataDrivenTesting.DDTesting_Better#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.DataDrivenTesting"}, {"name": "suite", "value": "DDTesting_Better"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "13948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.DataDrivenTesting.DDTesting_Better"}]}